version: "3.7"

services:

    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - balasolu-db:/var/lib/mysql
        secrets:
            - sql-username
            - sql-password
        environment:
            - MARIADB_USER_FILE=/run/secrets/sql-username
            - MARIADB_PASSWORD_FILE=/run/secrets/sql-password
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/sql-password
        restart: always
    
    web:
        depends_on:
            - mariadb
        build:
            context: .
            dockerfile: web-release.Dockerfile
        secrets:
            - sql-server
            - sql-username
            - sql-password
            - sql-database
            - smtp-host
            - smtp-port
            - smtp-username
            - smtp-password
            - smtp-fromname
            - smtp-fromaddress
            - discord-clientid
            - discord-clientsecret
        environment:
            - APPLICATION__SQLCLIENTOPTIONS__SERVER=/run/secrets/sql-server
            - APPLICATION__SQLCLIENTOPTIONS__USERNAME=/run/secrets/sql-username
            - APPLICATION__SQLCLIENTOPTIONS__PASSWORD=/run/secrets/sql-password
            - APPLICATION__SQLCLIENTOPTIONS__DATABASE=/run/secrets/sql-database
            - APPLICATION__SMTPCLIENTOPTIONS__HOST=/run/secrets/smtp-host
            - APPLICATION__SMTPCLIENTOPTIONS__PORT=/run/secrets/smtp-port
            - APPLICATION__SMTPCLIENTOPTIONS__USERNAME=/run/secrets/smtp-username
            - APPLICATION__SMTPCLIENTOPTIONS__PASSWORD=/run/secrets/smtp-password
            - APPLICATION__SMTPCLIENTOPTIONS__FROMNAME=/run/secrets/smtp-fromname
            - APPLICATION__SMTPCLIENTOPTIONS__FROMADDRESS=/run/secrets/smtp-fromaddress
            - APPLICATION__DISCORDOPTIONS__CLIENTID=/run/secrets/discord-clientid
            - APPLICATION__DISCORDOPTIONS__CLIENTSECRET=/run/secrets/discord-clientsecret
        restart: always

    nginx:
        depends_on:
            - mariadb
            - web
        build:
            context: .
            dockerfile: nginx-release.Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - balasolu-ssl:/etc/letsencrypt
        restart: always

secrets:
    sql-server:
        file: secrets/sql-server
    sql-username:
        file: secrets/sql-username
    sql-password:
        file: secrets/sql-password
    sql-database:
        file: secrets/sql-database
    smtp-host:
        file: secrets/smtp-host
    smtp-port:
        file: secrets/smtp-port
    smtp-username:
        file: secrets/smtp-username
    smtp-password:
        file: secrets/smtp-password
    smtp-fromname:
        file: secrets/smtp-fromname
    smtp-fromaddress:
        file: secrets/smtp-fromaddress
    discord-clientid:
        file: secrets/discord-clientid
    discord-clientsecret:
        file: secrets/discord-clientsecret
        
volumes:
    balasolu-db:
        external: true
    balasolu-ssl:
        external: true
